version: '2'

networks:
  default:
    driver: bridge

services:
  moodle:
    restart: always
    image: zgolus/moodle
    depends_on: 
      - mysql
    ports:
      - 180:80
      - 1443:443
      - 2222:2222
    environment:
      - DB_PORT_3306_TCP_ADDR=mysql
      - DB_ENV_MYSQL_USER=moodle
      - DB_ENV_MYSQL_PASSWORD=moodle
      - DB_ENV_MYSQL_DATABASE=moodle
      - MOODLE_URL=http://localhost:180
      - MOODLE_DATAROOT=/var/moodledata
    links:
      - mysql:myslq

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
    volumes: 
      - ./var/mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
